return {
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    opts = {
        -- A quiet, warm palette for long editing sessions.
        variant = "default",
        transparent = false,
        saturation = 0.82,
        italic_comments = true,
        colors = {
            bg = "#211712",
            bg_alt = "#2A1D16",
            bg_highlight = "#3A2A20",
            fg = "#EADFCC",
            grey = "#A99A88",
            blue = "#86AAA1",
            green = "#9DB58A",
            cyan = "#8BB9AF",
            red = "#D58A78",
            yellow = "#D6B578",
            magenta = "#C89AAA",
            pink = "#D99E9A",
            orange = "#D09A6B",
            purple = "#AB9AC0",
        },
        highlights = function(colors)
            return {
                -- Editor chrome
                CursorLine = { bg = "#2D2119" },
                Visual = { bg = "#49352A" },
                MatchParen = { fg = "#F4D79D", bg = "#3A2A20", bold = true },
                ColorColumn = { bg = "#2A1D16" },
                FloatBorder = { fg = "#695244", bg = colors.bg },
                Pmenu = { fg = colors.fg, bg = "#2A1D16" },
                PmenuSel = { fg = colors.fg, bg = "#49352A", bold = true },
                Search = { fg = "#211712", bg = "#D6B578" },
                IncSearch = { fg = "#211712", bg = "#D09A6B" },

                -- Syntax: restrained, but each token class remains distinct.
                Comment = { fg = "#A99A88", italic = true },
                Function = { fg = colors.blue },
                Keyword = { fg = colors.orange },
                Statement = { fg = colors.magenta },
                Type = { fg = colors.purple },
                String = { fg = colors.green },
                Number = { fg = colors.yellow },
                Boolean = { fg = colors.cyan },
                Constant = { fg = colors.pink },
                Operator = { fg = "#C4B29F" },
                PreProc = { fg = colors.cyan },

                ["@function"] = { fg = colors.blue },
                ["@function.call"] = { fg = colors.blue },
                ["@function.builtin"] = { fg = colors.cyan },
                ["@keyword"] = { fg = colors.orange },
                ["@keyword.function"] = { fg = colors.magenta },
                ["@type"] = { fg = colors.purple },
                ["@type.builtin"] = { fg = "#C5B2CC" },
                ["@property"] = { fg = "#D9C9B7" },
                ["@variable.builtin"] = { fg = colors.pink },
                ["@string.escape"] = { fg = colors.yellow },
                ["@tag"] = { fg = colors.magenta },
                ["@tag.attribute"] = { fg = colors.yellow },

                -- Diagnostics keep their urgency without neon contrast.
                DiagnosticError = { fg = colors.red },
                DiagnosticWarn = { fg = colors.yellow },
                DiagnosticInfo = { fg = colors.blue },
                DiagnosticHint = { fg = colors.cyan },
                DiagnosticVirtualTextError = { fg = colors.red },
                DiagnosticVirtualTextWarn = { fg = colors.yellow },
                DiagnosticVirtualTextInfo = { fg = colors.blue },
                DiagnosticVirtualTextHint = { fg = colors.cyan },
                DiagnosticUnderlineError = { sp = colors.red, undercurl = true },
                DiagnosticUnderlineWarn = { sp = colors.yellow, undercurl = true },
            }
        end,
    },
}
